  -- BIGS
INSERT INTO "profile" ("profile_type", "first_name", "last_name", "sex", "dob_or_age", "race", "address", "latitude", "longitude", "ems", "summary", "preference", "interest", "b_employer", "b_occupation", "b_marital_status")
VALUES
('1', 'Sam', 'Jones', '2', '32', 'White', '3904 Main Street, Kansas City, MO 64111', '39.0560072', '-94.5886469', 'Ima Matchmaker', 'Sam works as a nurse at Truman hospital, so he has some flexible hours. He likes to kayak and hike but also enjoys films with subtitles. Sam has a cat. Sam is a non-smoker and rarely drinks alcohol.  He was raised by a single mother here in Kansas City, but recently met his birth father for the first time and it was a positive experience. This was a big factor in motivating him to volunteer because not everyone gets a second chance at having a father.', '{"age": "Open", "race": "Open", "religion": "Open", "speak_english": "Open", "lvl_of_problems": "Open", "max_distance_miles": 15}', 'health & fitness, outdoors, foreign films, medicine, science', 'Truman Medical Center', 'Nurse', 'Single'),

('1', 'Wilma', 'Franklin', '1', '48', 'Chinese/White - biracial', '2114 Elma Street, Kansas City, MO 64124', '39.1097231', '-94.5566433', 'Ima Matchmaker', 'Wilma loves kids which is why she teaches music. She has a grown son and daughter who live out of state. Wilma was widowed last year after her husband had an aggressive cancer. Wilma has many friends and associates with the local performing arts scene and also serves on fundraising committees. Wilma likes dogs but is allergic so she cannot have one at home, instead she visits dog parks often - she does ok with allergy meds and a long shower after. She has spare instruments if the Little is interested in learning to play something. However, they do not have to like music. She is happy to introduce them to it, or not at all. She is willing to learn new things too and would welcome getting inspired by the interests of her Little. ', '{"age": "Open", "race": "Open", "religion": "Open", "speak_english": "Open", "lvl_of_problems": "Open", "max_distance_miles": 15}', 'theater, performance arts, concerts, taking train trips, visiting dog parks', 'Self-employed', 'Music Teacher', 'Widow'),

('3', 'Tamara and Michael', 'Ross', '3', '32, 28', 'African American', '6031 Cherry Street, Kansas City, MO 64110', '39.0173911', '-94.5812938', 'Ima Matchmaker', 'Tamara (32) and Michael (28) are wanting to eventually adopt a child but want to volunteer to better prepare them for adopting an older child. They love exploring Kansas City, discovering people, places, and things. They moved to KC 4 years ago from Memphis and intend to stay here. They are members of Calvary Temple Baptist Church and just started to teach Sunday School - also as a way to decide on what age and gender they would like to adopt and if they feel ready to adopt more than one child (siblings). They were emphatic that their decision to adopt in the future will not change their commitment to their Little. Michael occasionally smokes cigars. They both drink wine or beer, mostly when having dinner out or at a BBQ.', '{"age": "13-14", "race": "Open", "religion": "Open", "speak_english": "Open", "lvl_of_problems": "Open", "max_distance_miles": 29}', 'board games, BBQs, exploring all the water fountains in KC - they have a list and are trying to visit them all', 'City of Kansas City, Hilton', 'City Road Maintenance, Hotel Housekeeping Manager', 'Married'),

('1', 'Chad', 'Keese', '2', '57', 'White', '1119 E Missouri Avenue, Kansas City, MO 64106', '39.1096706', '-94.5694189', 'Ima Matchmaker', 'Chad works as a nurse at Truman hospital, so he has some flexible hours. He likes to kayak and hike but also enjoys films with subtitles. Chad has a cat. Chad is a non-smoker and rarely drinks alcohol.  He was raised by a single mother here in Kansas City, but recently met his birth father for the first time and it was a positive experience. This was a big factor in motivating him to volunteer because not everyone gets a second chance at having a father.', '{"age": "Open", "race": "Open", "religion": "Open", "speak_english": "Open", "lvl_of_problems": "Open", "max_distance_miles": 15}', 'health & fitness, outdoors, foreign films, medicine, science', 'Truman Medical Center', 'Nurse', 'Single'),

('1', 'Dinish', 'Patel', '2', '30', 'Asian', '2606 Campbell Street, Kansas City, MO 64108', '39.07927', '-94.5749652',  'Ima Matchmaker', 'Dinish works as a nurse at Truman hospital, so he has some flexible hours. He likes to kayak and hike but also enjoys films with subtitles. Dinish has a cat. Dinish is a non-smoker and rarely drinks alcohol.  He was raised by a single mother here in Kansas City, but recently met his birth father for the first time and it was a positive experience. This was a big factor in motivating him to volunteer because not everyone gets a second chance at having a father.', '{"age": "Open", "race": "Open", "religion": "Open", "speak_english": "Open", "lvl_of_problems": "Open", "max_distance_miles": 15}', 'health & fitness, outdoors, foreign films, medicine, science', 'Truman Medical Center', 'Nurse', 'Single'),

('1', 'Hector', 'Gonzales', '2', '37', 'Latino', '2127 Madison Avenue, Kansas City, MO 64108', '39.0866259', '-94.5952086', 'Ima Matchmaker', 'Hector works as a nurse at Truman hospital, so he has some flexible hours. He likes to kayak and hike but also enjoys films with subtitles. Hector has a cat. Hector is a non-smoker and rarely drinks alcohol.  He was raised by a single mother here in Kansas City, but recently met his birth father for the first time and it was a positive experience. This was a big factor in motivating him to volunteer because not everyone gets a second chance at having a father.', '{"age": "Open", "race": "Open", "religion": "Open", "speak_english": "Open", "lvl_of_problems": "Open", "max_distance_miles": 15}', 'health & fitness, outdoors, foreign films, medicine, science', 'Truman Medical Center', 'Nurse', 'Single'),

('1', 'Katie', 'Poppa', '1', '28', 'White', '4432 Wyoming Street, Kansas City, MO 64111', '39.0470611', '-94.605421', 'Ima Matchmaker', 'Katie loves kids which is why she teaches music. She has a grown son and daughter who live out of state. Katie was widowed last year after her husband had an aggressive cancer. Katie has many friends and associates with the local performing arts scene and also serves on fundraising committees. Katie likes dogs but is allergic so she cannot have one at home, instead she visits dog parks often - she does ok with allergy meds and a long shower after. She has spare instruments if the Little is interested in learning to play something. However, they do not have to like music. She is happy to introduce them to it, or not at all. She is willing to learn new things too and would welcome getting inspired by the interests of her Little. ', '{"age": "Open", "race": "Open", "religion": "Open", "speak_english": "Open", "lvl_of_problems": "Open", "max_distance_miles": 15}', 'theater, performance arts, concerts, taking train trips, visiting dog parks', 'Self-employed', 'Music Teacher', 'Widow'),

('1', 'Debo', 'Pullara', '1', '23', 'African American', '1020 NE Lindberg Dr, Kansas City, MO 64118', '39.2090763', '-94.5689689', 'Ima Matchmaker', 'Debo loves kids which is why she teaches music. She has a grown son and daughter who live out of state. Debo was widowed last year after her husband had an aggressive cancer. Debo has many friends and associates with the local performing arts scene and also serves on fundraising committees. Debo likes dogs but is allergic so she cannot have one at home, instead she visits dog parks often - she does ok with allergy meds and a long shower after. She has spare instruments if the Little is interested in learning to play something. However, they do not have to like music. She is happy to introduce them to it, or not at all. She is willing to learn new things too and would welcome getting inspired by the interests of her Little. ', '{"age": "Open", "race": "Open", "religion": "Open", "speak_english": "Open", "lvl_of_problems": "Open", "max_distance_miles": 15}', 'theater, performance arts, concerts, taking train trips, visiting dog parks', 'Self-employed', 'Music Teacher', 'Widow'),

('1', 'Shelley', 'Sipes', '1', '45', 'White', '2419 S Norwood Avenue, Independence, MO 64052', '39.0762051', '-94.4428537','Ima Matchmaker', 'Shelley loves kids which is why she teaches music. She has a grown son and daughter who live out of state. Shelley was widowed last year after her husband had an aggressive cancer. Shelley has many friends and associates with the local performing arts scene and also serves on fundraising committees. Shelley likes dogs but is allergic so she cannot have one at home, instead she visits dog parks often - she does ok with allergy meds and a long shower after. She has spare instruments if the Little is interested in learning to play something. However, they do not have to like music. She is happy to introduce them to it, or not at all. She is willing to learn new things too and would welcome getting inspired by the interests of her Little. ', '{"age": "Open", "race": "Open", "religion": "Open", "speak_english": "Open", "lvl_of_problems": "Open", "max_distance_miles": 15}', 'theater, performance arts, concerts, taking train trips, visiting dog parks', 'Self-employed', 'Music Teacher', 'Widow'),

('3', 'Cheri and Ling', 'Xu', '3', '37, 37', 'Asian', '2121 Central Street, Unit #33, Kansas City, MO 64108', '39.0873619', '-94.5872598','Ima Matchmaker', 'Cheri (37) and Ling (37) are wanting to eventually adopt a child but want to volunteer to better prepare them for adopting an older child. They love exploring Kansas City, discovering people, places, and things. They moved to KC 4 years ago from Memphis and intend to stay here. They are members of Calvary Temple Baptist Church and just started to teach Sunday School - also as a way to decide on what age and gender they would like to adopt and if they feel ready to adopt more than one child (siblings). They were emphatic that their decision to adopt in the future will not change their commitment to their Little. Ling occasionally smokes cigars. They both drink wine or beer, mostly when having dinner out or at a BBQ.', '{"age": "13-14", "race": "Open", "religion": "Open", "speak_english": "Open", "lvl_of_problems": "Open", "max_distance_miles": 15}', 'board games, BBQs, exploring all the water fountains in KC - they have a list and are trying to visit them all', 'City of Kansas City, Hilton', 'City Road Maintenance, Hotel Housekeeping Manager', 'Married'),

('3', 'Kiahana  and Phil', 'Kennedy', '3', '26, 27', 'African American, White', '2522 College Avenue, Kansas City, MO 64127', '39.07959', '-94.5470496','Ima Matchmaker', 'Kiahana (26) and Phil (27) are wanting to eventually adopt a child but want to volunteer to better prepare them for adopting an older child. They love exploring Kansas City, discovering people, places, and things. They moved to KC 4 years ago from Memphis and intend to stay here. They are members of Calvary Temple Baptist Church and just started to teach Sunday School - also as a way to decide on what age and gender they would like to adopt and if they feel ready to adopt more than one child (siblings). They were emphatic that their decision to adopt in the future will not change their commitment to their Little. Phil occasionally smokes cigars. They both drink wine or beer, mostly when having dinner out or at a BBQ.', '{"age": "13-14", "race": "Open", "religion": "Open", "speak_english": "Open", "lvl_of_problems": "Open", "max_distance_miles": 15}', 'board games, BBQs, exploring all the water fountains in KC - they have a list and are trying to visit them all', 'City of Kansas City, Hilton', 'City Road Maintenance, Hotel Housekeeping Manager', 'Married'),

('3', 'Vanessa and Martin', 'Connors', '3', '40, 43', 'African American', '235 Ward Pkwy #514, Kansas City, MO 64112', '39.0389125', '-94.5919554', 'Ima Matchmaker', 'Vanessa (40) and Martin (43) are wanting to eventually adopt a child but want to volunteer to better prepare them for adopting an older child. They love exploring Kansas City, discovering people, places, and things. They moved to KC 4 years ago from Memphis and intend to stay here. They are members of Calvary Temple Baptist Church and just started to teach Sunday School - also as a way to decide on what age and gender they would like to adopt and if they feel ready to adopt more than one child (siblings). They were emphatic that their decision to adopt in the future will not change their commitment to their Little. Martin occasionally smokes cigars. They both drink wine or beer, mostly when having dinner out or at a BBQ.', '{"age": "13-14", "race": "Open", "religion": "Open", "speak_english": "Open", "lvl_of_problems": "Open", "max_distance_miles": 15}', 'board games, BBQs, exploring all the water fountains in KC - they have a list and are trying to visit them all', 'City of Kansas City, Hilton', 'City Road Maintenance, Hotel Housekeeping Manager', 'Married');

-- LITTLES
INSERT INTO "profile" ("profile_type", "first_name", "last_name", "sex", "dob_or_age", "race", "address", "latitude", "longitude", "ems", "summary", "preference", "interest", "l_parent", "l_parent_relationship_to_child")
VALUES
('2', 'Demonta', 'Miller', '2', '8', 'African American', '3514 Tracy Avenue, Kansas City, MO 64109', '39.0628069','-94.5694119', 'Juana Betterlife', 'Demonta is curious about how things work. His adult brother (25 yrs old) takes him to the electronics section of thrift stores and Demonta picks out things to take apart and put back together like radios and VCR players. His uncle is in the military and expects to be deployed so the family wants Demonta to have a male role model to ease the transition as he and his brother are close. The Big/Little relationship will continue regardless of the potential for deployment. Demonta has dyslexia and wants to be able to read better because he likes science. There is a set of encyclopedias in the house and he really wants to do more than look at the pictures. The only sport he likes is kickball, and was very emphatic that he does not like soccer and the two are not the same. Demonta also has a good sense of humor, the first thing he wanted to do was tell me a joke.', '{"age": "23-27", "race": "OPEN", "religion": "OPEN", "sexuality": "OPEN", "smoking_drinking": "OPEN", "children": "Open", "pets": "OPEN", "weapons": "OPEN", "big_couple": "n/a", "big_sister": "n/a"}', 'electronics, reading, jokes and funny things, kickball, science', 'Betty', 'Mother'),

('2', 'Jason', 'Twinada', '2', '12', 'Japanese American', '1015 Norton Avenue, Kansas City, MO 64127', '39.1000564','-94.5345545', 'Juana Betterlife', 'Jason is very outgoing when he is at school or his martial arts class, with those exceptions he is very quiet and introspective. Jason lived with an uncle for 10 years but was removed from that household when his father was released from prison. The uncle was physically abusive but the father is not. Jason learned to have a low profile at home to avoid punishments. He would really like a dog but cannot have one in the apartment they live in, so he is really hoping his Big will have a dog or several dogs. Jason participated in a read-to-a-dog campaign at his school and wanted to be able to do that at home too.', '{"age": "OPEN", "race": "OPEN", "religion": "OPEN", "sexuality": "OPEN", "smoking_drinking": "No smoking, uncle smoked and Jason has a negative association.", "children": "Open", "pets": "Dogs", "weapons": "OPEN", "big_couple": "n/a", "big_sister": "n/a"}', 'martial arts, reading, likes to build things, country music', 'James', 'Father'),

('2', 'Justin', 'Brenner', '2', '6', 'White', '505 Gallatin Street #6, Liberty, MO 64068', '39.2519022', '-94.4237584', 'Juana Betterlife', 'Justin is curious about how things work. His adult brother (25 yrs old) takes him to the electronics section of thrift stores and Justin picks out things to take apart and put back together like radios and VCR players. His uncle is in the military and expects to be deployed so the family wants Justin to have a male role model to ease the transition as he and his brother are close. The Big/Little relationship will continue regardless of the potential for deployment. Justin has dyslexia and wants to be able to read better because he likes science. There is a set of encyclopedias in the house and he really wants to do more than look at the pictures. The only sport he likes is kickball, and was very emphatic that he does not like soccer and the two are not the same. Justin also has a good sense of humor, the first thing he wanted to do was tell me a joke.', '{"age": "21-25", "race": "OPEN", "religion": "OPEN", "sexuality": "OPEN", "smoking_drinking": "OPEN", "children": "Open", "pets": "OPEN", "weapons": "OPEN", "big_couple": "n/a", "big_sister": "n/a"}', 'electronics, reading, jokes and funny things, kickball, science', 'Betty', 'Mother'),

('2', 'Xavier', 'Davis', '2', '14', 'African American', '11303 Kensington Avenue, Kansas City, MO 64137', '38.9204966', '-94.5480903', 'Juana Betterlife', 'Xavier is very outgoing when he is at school or his martial arts class, with those exceptions he is very quiet and introspective. Xavier lived with an uncle for 10 years but was removed from that household when his father was released from prison. The uncle was physically abusive but the father is not. Xavier learned to have a low profile at home to avoid punishments. He would really like a dog but cannot have one in the apartment they live in, so he is really hoping his Big will have a dog or several dogs. Xavier participated in a read-to-a-dog campaign at his school and wanted to be able to do that at home too.', '{"age": "OPEN", "race": "OPEN", "religion": "OPEN", "sexuality": "OPEN", "smoking_drinking": "No smoking.", "children": "Open", "pets": "Dogs", "weapons": "OPEN", "big_couple": "n/a", "big_sister": "n/a"}', 'martial arts, reading, likes to build things, country music', 'James', 'Father'),

('2', 'Owen', 'Moore', '2', '11', 'African American', '104 NE Knox Street, Blue Springs, MO 64014', '39.0199684', '-94.2626554', 'Juana Betterlife', 'Owen is curious about how things work. His adult brother (25 yrs old) takes him to the electronics section of thrift stores and Owen picks out things to take apart and put back together like radios and VCR players. His uncle is in the military and expects to be deployed so the family wants Owen to have a male role model to ease the transition as he and his brother are close. The Big/Little relationship will continue regardless of the potential for deployment. Owen has dyslexia and wants to be able to read better because he likes science. There is a set of encyclopedias in the house and he really wants to do more than look at the pictures. The only sport he likes is kickball, and was very emphatic that he does not like soccer and the two are not the same. Owen also has a good sense of humor, the first thing he wanted to do was tell me a joke.', '{"age": "23-28", "race": "OPEN", "religion": "OPEN", "sexuality": "OPEN", "smoking_drinking": "OPEN", "children": "Open", "pets": "OPEN", "weapons": "OPEN", "big_couple": "n/a", "big_sister": "n/a"}', 'electronics, reading, jokes and funny things, kickball, science', 'Betty', 'Mother'),

('2', 'Max', 'Harris', '2', '9', 'Hispanic', '5306 Laurel Avenue, Raytown, MO 64133', '39.0265373', '-94.4752592', 'Juana Betterlife', 'Max is very outgoing when he is at school or his martial arts class, with those exceptions he is very quiet and introspective. Max lived with an uncle for 10 years but was removed from that household when his father was released from prison. The uncle was physically abusive but the father is not. Max learned to have a low profile at home to avoid punishments. He would really like a dog but cannot have one in the apartment they live in, so he is really hoping his Big will have a dog or several dogs. Max participated in a read-to-a-dog campaign at his school and wanted to be able to do that at home too.', '{"age": "OPEN", "race": "OPEN", "religion": "OPEN", "sexuality": "OPEN", "smoking_drinking": "No smoking.", "children": "Open", "pets": "Dogs", "weapons": "OPEN", "big_couple": "n/a", "big_sister": "n/a"}', 'martial arts, reading, likes to build things, country music', 'James', 'Father'),

('2', 'Elijah', 'Taylor', '2', '10', 'African American', '2929 Park Avenue E, Kansas City, MO 64109', '39.0725811','-94.5569916', 'Juana Betterlife', 'Elijah is curious about how things work. His adult brother (25 yrs old) takes him to the electronics section of thrift stores and Elijah picks out things to take apart and put back together like radios and VCR players. His uncle is in the military and expects to be deployed so the family wants Elijah to have a male role model to ease the transition as he and his brother are close. The Big/Little relationship will continue regardless of the potential for deployment. Elijah has dyslexia and wants to be able to read better because he likes science. There is a set of encyclopedias in the house and he really wants to do more than look at the pictures. The only sport he likes is kickball, and was very emphatic that he does not like soccer and the two are not the same. Elijah also has a good sense of humor, the first thing he wanted to do was tell me a joke.', '{"age": "OPEN", "race": "OPEN", "religion": "OPEN", "sexuality": "OPEN", "smoking_drinking": "OPEN", "children": "Open", "pets": "OPEN", "weapons": "OPEN", "big_couple": "n/a", "big_sister": "n/a"}', 'electronics, reading, jokes and funny things, kickball, science', 'Betty', 'Mother'),

('2', 'Rick', 'Lewis', '2', '11', 'African American', '3006 Montgall Avenue, Kansas City, MO 64128', '39.071205', '-94.5541241', 'Juana Betterlife', 'Rick is very outgoing when he is at school or his martial arts class, with those exceptions he is very quiet and introspective. Rick lived with an uncle for 10 years but was removed from that household when his father was released from prison. The uncle was physically abusive but the father is not. Rick learned to have a low profile at home to avoid punishments. He would really like a dog but cannot have one in the apartment they live in, so he is really hoping his Big will have a dog or several dogs. Rick participated in a read-to-a-dog campaign at his school and wanted to be able to do that at home too.', '{"age": "OPEN", "race": "OPEN", "religion": "OPEN", "sexuality": "OPEN", "smoking_drinking": "No, the uncle smoked and Rick has a negative association", "children": "Open", "pets": "Only Dogs", "weapons": "OPEN", "big_couple": "n/a", "big_sister": "n/a"}', 'martial arts, reading, likes to build things, country music', 'James', 'Father'),

('2', 'Kalinda', 'Jones', '1', '13', 'White', '2317 Wabash Avenue, Kansas City, MO 64127', '39.0834741','-94.5533731', 'Juana Betterlife', 'Kalinda is struggling with home life. Her father has sole custody but Kalinda sneaks in unsanctioned unsupervised visits with her mom, who has significant substance abuse issues. Kalinda is a below average student and is having trouble adjusting to the idea of going to high school soon and the additional responsibilities that will require. She hopes to go to college to study art but has trouble being disciplined in completing her assignments in all her other classes. Kalinda says the inspiration for her art comes to her in her dreams, and that she dreams in color.', '{"age": "OPEN", "race": "OPEN", "religion": "OPEN", "sexuality": "OPEN", "smoking_drinking": "OPEN", "children": "Open", "pets": "OPEN", "weapons": "OPEN", "big_couple": "n/a", "big_sister": "n/a"}', 'art, drawing, painting, museums, art galleries, art books, art supply shopping', 'Marcus', 'Father'),

('2', 'Maria', 'Torres', '1', '10', 'Hispanic', '2714 Cypress Avenue, Kansas City, MO 64128', '39.0756894','-94.5305843', 'Juana Betterlife', 'Maria is an only child, her mother died in childbirth. Her father is still single. She has aunts, and a grandmother locally but there is a lot of family drama and it plays into how much time they are willing to spend with her. Her father would like to have a stable female outside the family that Maria can depend on, especially when the family is at odds. Maria loves animals and would like to volunteer at a shelter, so if the Big is interested in that as well, she is hoping that could be a regular activity. ', '{"age": "OPEN", "race": "OPEN", "religion": "OPEN", "sexuality": "OPEN", "smoking_drinking": "No smoking, tobacco allergy", "children": "Open", "pets": "Yes please, any pets.", "weapons": "OPEN", "big_couple": "n/a", "big_sister": "n/a"}', 'YouTube videos on fancy hairstyles, all animals, dancing, cooking', 'Francisco', 'Father'),

('2', 'Mia', 'Hughes', '1', '12', 'Hispanic', '2528 Oakley Avenue, Kansas City, MO 64127', '39.0786342', '-94.5203878', 'Juana Betterlife', 'Mia is struggling with home life. Her father has sole custody but Mia sneaks in unsanctioned unsupervised visits with her mom, who has significant substance abuse issues. Mia is a below average student and is having trouble adjusting to the idea of going to high school soon and the additional responsibilities that will require. She hopes to go to college to study art but has trouble being disciplined in completing her assignments in all her other classes. Mia says the inspiration for her art comes to her in her dreams, and that she dreams in color.', '{"age": "OPEN", "race": "OPEN", "religion": "OPEN", "sexuality": "OPEN", "smoking_drinking": "OPEN", "children": "Open", "pets": "OPEN", "weapons": "OPEN", "big_couple": "n/a", "big_sister": "n/a"}', 'art, drawing, painting, museums, art galleries, art books, art supply shopping', 'Marcus', 'Father'),

('2', 'Ellie', 'Long', '1', '8', 'White', '316 Lawn Avenue, Kansas City, MO 64124', '39.1102747', '-94.5294884', 'Juana Betterlife', 'Ellie is an only child, her mother died in childbirth. Her father is still single. She has aunts, and a grandmother locally but there is a lot of family drama and it plays into how much time they are willing to spend with her. Her father would like to have a stable female outside the family that Ellie can depend on, especially when the family is at odds. Ellie loves animals and would like to volunteer at a shelter, so if the Big is interested in that as well, she is hoping that could be a regular activity. ', '{"age": "OPEN", "race": "OPEN", "religion": "OPEN", "sexuality": "OPEN", "smoking_drinking": "No smoking", "children": "Open", "pets": "OPEN", "weapons": "OPEN", "big_couple": "n/a", "big_sister": "n/a"}', 'YouTube videos on fancy hairstyles, all animals, dancing, cooking', 'Francisco', 'Father'),

('2', 'Aaliyah', 'Price', '1', '13', 'Asian', '9801 Kessler Street, Overland Park, Kansas 66212', '38.9510059', '-94.6929653', 'Juana Betterlife', 'Aaliyah is struggling with home life. Her father has sole custody but Aaliyah sneaks in unsanctioned unsupervised visits with her mom, who has significant substance abuse issues. Aaliyah is a below average student and is having trouble adjusting to the idea of going to high school soon and the additional responsibilities that will require. She hopes to go to college to study art but has trouble being disciplined in completing her assignments in all her other classes. Aaliyah says the inspiration for her art comes to her in her dreams, and that she dreams in color.', '{"age": "OPEN", "race": "OPEN", "religion": "OPEN", "sexuality": "OPEN", "smoking_drinking": "OPEN", "children": "Open", "pets": "OPEN", "weapons": "OPEN", "big_couple": "n/a", "big_sister": "n/a"}', 'art, drawing, painting, museums, art galleries, art books, art supply shopping', 'Marcus', 'Father'),

('2', 'Azami', 'King', '1', '8', 'Asian', '1840 S St Paul Street, Kansas City, Kansas 66103', '39.0683755', '-94.6247661', 'Juana Betterlife', 'Ellie is an only child, her mother died in childbirth. Her father is still single. She has aunts, and a grandmother locally but there is a lot of family drama and it plays into how much time they are willing to spend with her. Her father would like to have a stable female outside the family that Azami can depend on, especially when the family is at odds. Azami loves animals and would like to volunteer at a shelter, so if the Big is interested in that as well, she is hoping that could be a regular activity. ', '{"age": "OPEN", "race": "OPEN", "religion": "OPEN", "sexuality": "OPEN", "smoking_drinking": "No smoking, lung cancer in family", "children": "Open", "pets": "OPEN", "weapons": "OPEN", "big_couple": "n/a", "big_sister": "n/a"}', 'YouTube videos on fancy hairstyles, all animals, dancing, cooking', 'Francisco', 'Father'),

('2', 'Kayla', 'Garcia', '1', '16', 'Hispanic', '4341 Fisher Street, Kansas City, Kansas 66103', '39.0482183', '-94.6178275', 'Juana Betterlife', 'Kayla is struggling with home life. Her father has sole custody but Kayla sneaks in unsanctioned unsupervised visits with her mom, who has significant substance abuse issues. Kayla is a below average student and is having trouble adjusting to the idea of going to high school soon and the additional responsibilities that will require. She hopes to go to college to study art but has trouble being disciplined in completing her assignments in all her other classes. Kayla says the inspiration for her art comes to her in her dreams, and that she dreams in color.', '{"age": "OPEN", "race": "OPEN", "religion": "OPEN", "sexuality": "OPEN", "smoking_drinking": "OPEN", "children": "Open", "pets": "Yes please, she loves pets", "weapons": "OPEN", "big_couple": "n/a", "big_sister": "n/a"}', 'art, drawing, painting, museums, art galleries, art books, art supply shopping', 'Marcus', 'Father'),

('2', 'Lulu', 'Young', '1', '7', 'African American', '2725 Askew Avenue, Kansas City, MO 64128', '39.0757254','-94.5429215', 'Juana Betterlife', 'Lulu is an only child, her mother died in childbirth. Her father is still single. She has aunts, and a grandmother locally but there is a lot of family drama and it plays into how much time they are willing to spend with her. Her father would like to have a stable female outside the family that Lulu can depend on, especially when the family is at odds. Lulu loves animals and would like to volunteer at a shelter, so if the Big is interested in that as well, she is hoping that could be a regular activity. ', '{"age": "OPEN", "race": "OPEN", "religion": "OPEN", "sexuality": "OPEN", "smoking_drinking": "OPEN", "children": "Open", "pets": "OPEN", "weapons": "OPEN", "big_couple": "n/a", "big_sister": "n/a"}', 'YouTube videos on fancy hairstyles, all animals, dancing, cooking', 'Francisco', 'Father');


-- REVIEW
INSERT INTO "status"
    ("big_id", "little_id", "review", "comment")
VALUES
('4', '8', '3', 'A good fit because Sam and Jason are both establishing new relationships with their fathers.'), 
('4', '7', '2', 'There could be potential here. Although Sam''s science background could work well with Demonta''s curiosity, Sam is a little older than Demonta''s mother prefers.'), 
('5', '9', '2', 'Although their art preferences differ, studio vs. performing, these two are both creative people. Wilma has reservations about Kalinda sneaking out and is not sure she is ready to take on a teenager.'), 
('5', '10', '3', 'Both express an interest in dogs, but neither can have one. It could be a strong bonding factor.  Maria would do well to have a consistent independent woman role model to contrast the drama and codependencies in her current family dynamic. We think Maria would take to the performing arts with opportunities to costuming, makeup, etc.'), 
('6', '7', '3', 'Michael is close in age to Demonta''s brother. The Ross family hopes they can use their love for games to help Demonta find strategies to deal with the dyslexia.'), 
('6', '8', '1', 'Michael''s cigar smoking might/might not be an issue. If this potential match is considered in the future, it should be discussed.'), 
('6', '9', '2', 'Kalinda wasn''t a strong fit for Tamara, so they opted for Demonta since Michael was a good pairing.'), 
('6', '10', '2', 'There were no issues with this possible pairing, but there was more connection potential with another Big.');